[project]
name = "credit-scoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlflow>=3.3.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
